# Generated by Django 5.0.7 on 2024-07-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_messages_delete_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
