# Generated by Django 5.0.7 on 2024-12-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_profile_bio_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, default='Enter Your Email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, default='Enter Your Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(blank=True, default='Enter Your Phone Number', max_length=15),
        ),
    ]
